import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:aauraluxe/app/data/models/models.dart';
import 'package:aauraluxe/app/data/providers/order_api.dart';
import 'package:aauraluxe/app/modules/customer/cart/controllers/cart_controller.dart';
import 'package:aauraluxe/app/modules/auth/controllers/auth_controller.dart';
import 'package:aauraluxe/app/routes/app_routes.dart';

class CheckoutController extends GetxController {
  final OrderApi _orderApi = Get.put(OrderApi());
  final CartController _cartController = Get.find<CartController>();
  final AuthController _authController = Get.find<AuthController>();

  final formKey = GlobalKey<FormState>();
  final nameController = TextEditingController();
  final phoneController = TextEditingController();
  final emailController = TextEditingController();
  final addressController = TextEditingController();
  
  final isProcessing = false.obs;
  final paymentMethod = 'COD'.obs;

  @override
  void onInit() {
    super.onInit();
    _prefillFields();
  }

  void _prefillFields() {
    if (_authController.isAuthenticated) {
      emailController.text = _authController.profile?.email ?? '';
    }
  }

  @override
  void onClose() {
    nameController.dispose();
    phoneController.dispose();
    emailController.dispose();
    addressController.dispose();
    super.onClose();
  }

  Future<void> submitOrder() async {
    if (!formKey.currentState!.validate()) return;
    if (_cartController.isEmpty) {
      Get.snackbar('Error', 'Your bag is empty.', snackPosition: SnackPosition.BOTTOM);
      return;
    }

    isProcessing.value = true;
    try {
      // Create order model
      final order = Order(
        id: 0, // Generated by database sequence
        userId: _authController.isAuthenticated ? _authController.profile!.id : null,
        customerName: nameController.text.trim(),
        customerPhone: phoneController.text.trim(),
        customerEmail: emailController.text.trim().isEmpty ? null : emailController.text.trim(),
        shippingAddress: addressController.text.trim(),
        paymentMethod: paymentMethod.value,
        status: 'pending',
        totalAmount: _cartController.total,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        items: [],
      );

      // Create OrderItems from cart items
      final items = _cartController.cartItems.map((cartItem) {
        return OrderItem(
          id: '',
          orderId: 0,
          productId: cartItem.product.id,
          productTitle: cartItem.product.title,
          quantity: cartItem.quantity,
          unitPrice: cartItem.product.effectivePrice,
          totalPrice: cartItem.totalPrice,
        );
      }).toList();

      // Send to API client
      final placedOrder = await _orderApi.placeOrder(order, items);

      // Success! Clear the shopping cart
      _cartController.clearCart();

      // Show congratulations dialog
      _showSuccessDialog(placedOrder.id);
    } catch (e) {
      Get.snackbar('Order Failed', 'Could not place order: $e', snackPosition: SnackPosition.BOTTOM);
    } finally {
      isProcessing.value = false;
    }
  }

  void _showSuccessDialog(int orderId) {
    Get.dialog(
      AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Row(
          children: [
            Icon(Icons.check_circle, color: Colors.green, size: 28),
            SizedBox(width: 8),
            Text('Order Confirmed'),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Thank you for shopping with AuraLuxe!', style: TextStyle(fontWeight: FontWeight.w600)),
            const SizedBox(height: 12),
            Text('Your order ID is: #$orderId', style: const TextStyle(fontSize: 15, color: Colors.black)),
            const SizedBox(height: 8),
            const Text('You can use this ID to track your order shipping progress in the "Track Order" page.', style: TextStyle(fontSize: 13, color: Colors.grey)),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () {
              Get.offAllNamed(AppRoutes.CUSTOMER_HOME);
            },
            child: const Text('Back to Home', style: TextStyle(color: Colors.black)),
          ),
          ElevatedButton(
            onPressed: () {
              Get.offAllNamed(AppRoutes.ORDER_TRACKING, arguments: {
                'orderId': orderId,
                'phone': phoneController.text.trim(),
              });
            },
            child: const Text('Track Order'),
          ),
        ],
      ),
      barrierDismissible: false,
    );
  }
}
