name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # You can specify a flutter-version if needed, e.g.:
          # flutter-version: '3.19.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web Application
        # Builds the web application. Adjust --base-href if you are using a custom domain.
        run: flutter build web --release --base-href "/aauraluxe/"

      - name: Create 404 fallback page for routing
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
